### ISSUE TITLE
Height inline style should have !important to override everything

### ISSUE THREAD

**Issue by emdotem** [Andarist/react-textarea-autosize#276]
In my widget I had to use !important everywhere to reset the style of the parent. By doing that, when the autoresizer sets the inline style, it doesn't get overridden because of the !important tag.

Can I contribute to add it?

**Comment by emdotem** [comment]
Sure. I have a reset css to all component inside my widget, something like this:

```css
.widget *{
    ....
    height: auto !important
}
```

Then, I override this value with this:
```css
.my-textarea{
    height: 52px !important;
}
```

And then I let `my-textarea` resize using autoresize. The issue is that the inline style this library sets, doesn't override these 2 values above.
